; Definitions of recognized categories:
; (NUMBER, TOTAL BYTES OF DEFINITION, PREDEFINED LENGTH,
; LENGHT1, LENGHT2, STATS, NAME)

CATEGORY:
#2,8,0,2,2,4,
; List of items:

Ip_LoadSave
Ip_Splash
Ip_MainDoorleft
Ip_MainDoorRight
Ip_MainLandscape
Ip_CreditsScroll
Ip_TitleTheEnd
Ip_CharacterInfo
Ip_CharacterDead
Ip_Spellactions
Ip_Itemsactions
Ip_Switchs
Free12
Ip_MovementArrows
Ip_DamageDoneBig
Ip_DamageReceived
Ip_DamageReceivedBig
Ip_CharacterSheet
Ip_RightArrowSpells
Ip_BackspaceSpells
Ip_InfoProperties
Free21
Ip_BlackSpaceTiny
Ip_InfoScroll
Free24
Ip_InfoChest
Ip_CharacterPictures
Ip_RenameScreen
Ip_FighterPositions
Ip_InfoObjectCircle
Ip_TitleFood
Ip_TitleWater
Ip_TitlePoisonned
Ip_CaseEmpty
Ip_CaseWounded
Ip_CaseSelected
Ip_CaseWhite
Ip_BlueProtected
Ip_GreenProtected
Ip_CyanProtected
Ip_RessurecScreen
Ds_MAGIC_VISION
Ii_ItemsStates
Ii_Weapons
Ii_clothesLegBody
Ii_clothesHeadFeetNeckShields
Ii_potionsMisc_
Ii_KeysFood
Ii_LimbsEyeMouthMisc_
DF_Pit_S3L
DF_Pit_F3L
DF_Pit_F3
DF_Pit_F2L
DF_Pit_F2
DF_Pit_F1L
DF_Pit_F1
DF_Pit_F0L
DF_Pit_F0
DF_Pit_INVISIBLE_F2L
DF_Pit_INVISIBLE_F2
DF_Pit_INVISIBLE_F1L
DF_Pit_INVISIBLE_F1
DF_Pit_INVISIBLE_F0L
DF_Pit_INVISIBLE_F0
DC_Pit_F2R
DC_Pit_F2
DC_Pit_F1R
DC_Pit_F1
DC_Pit_F0R
DC_Pit_F0
Dmask_wall_S3L
Dmask_wall_F3L
Dmask_wall_S2L
Dmask_wall_F2L
Dmask_wall_F1L
Dmask_wall_F0L
DT_TELEPORTER_F1
DT_FLUXCAGE_F1
DT_FLOOR
DT_CEILING
Free80
Free81
Free82
Free83
Free84
Free85
DD_wall_F1
DD_wall_S1
DD_wall_S2
DD_wall_S3
DD_wall_S3L
Something.bmp
Something.bmp
DT_wall_F0R
DT_wall_F0L
DT_wall_F1R
DT_wall_F1L
DT_wall_F1
DT_wall_S2R
DT_wall_S2L
DT_wall_F2R
DT_wall_F2L
DT_wall_F2
DT_wall_S3R
DT_wall_S3L
DT_wall_F3R
DT_wall_F3L
DT_wall_F3
DT_StairsUP_F3L
DT_StairsUP_F3
DT_StairsUP_F2L
DT_StairsUP_F2
DT_StairsUP_F1L
DT_StairsUP_F1
DT_StairsUP_F0
DT_StairsDOWN_F3L
DT_StairsDOWN_F3
DT_StairsDOWN_F2L
DT_StairsDOWN_F2
DT_StairsDOWN_F1L
DT_StairsDOWN_F1
DT_StairsDOWN_F0
DT_Stairs_S3L
DT_StairsUP_S2L
DT_StairsDOWN_S2L
DT_Stairs_S1
Free126
Free127
Free128
Free129
Free130
Free131
Free132
Free133
Free134
Free135
Free136
Free137
Free138
Free139
Free140
Free141
Free142
Free143
Free144
Free145
Free146
Free147
Free148
Free149
Free150
Free151
Free152
Free153
Free154
Free155
Free156
Free157
Free158
Free159
Free160
Free161
Free162
Free163
Free164
Free165
Free166
Free167
Free168
Free169
Free170
Free171
Free172
Free173
Free174
Free175
Free176
Free177
Free178
Free179
Free180
Free181
Free182
Free183
Free184
Free185
Free186
Free187
Free188
Free189
Free190
Free191
Free192
Free193
Free194
Free195
Free196
Free197
Free198
Free199
Free200
Free201
Free202
Free203
Free204
Free205
Free206
Free207
Free208
Free209
Free210
Free211
Free212
Free213
Free214
Free215
Free216
Free217
Free218
Free219
Free220
Free221
Free222
Free223
Free224
Free225
Free226
Free227
Free228
Free229
Free230
Free231
Free232
Free233
Free234
Free235
Free236
Free237
Free238
Free239
Free240
Free241
Free242
Free243
Free244
Free245
DD_PORTCULLIS_F3
DD_PORTCULLIS_F2
DD_PORTCULLIS_F1
DD_WOODEN_F3
DD_WOODEN_F2
DD_WOODEN_F1
DD_IRON_F3
DD_IRON_F2
DD_IRON_F1
DD_RA_F3
DD_RA_F2
DD_RA_F1
DW_TEXT_F1
DW_TEXT_S1
DW_TEXT_F2
DW_Alcove_SQUARE_S1
DW_Alcove_SQUARE_F1
DW_Alcove_VI_ALTAR_S1
DW_Alcove_VI_ALTAR_F1
DW_Alcove_ORNATE_S1
DW_Alcove_ORNATE_F1
DW_Decoration_HOOK_S1
DW_Decoration_HOOK_F1
DW_Keyhole_PLAIN_S1
DW_Keyhole_PLAIN_F1
DW_Decoration_RING_1_S1
DW_Decoration_RING_1_F1
DW_Switch_SMALL_S1
DW_Switch_SMALL_F1
DW_Decoration_DENT_1_S1
DW_Decoration_DENT_1_F1
DW_Decoration_DENT_2_S1
DW_Decoration_DENT_2_F1
DW_Decoration_RING_2_S1
DW_Decoration_RING_2_F1
DW_Decoration_CRACK_S1
DW_Decoration_CRACK_F1
DW_Decoration_SLIME_OUTLET_S1
DW_Decoration_SLIME_OUTLET_F1
DW_Decoration_DENT_3_S1
DW_Decoration_DENT_3_F1
DW_Switch_TINY_OUT_S1
DW_Switch_TINY_OUT_F1
DW_Switch_GREEN_OUT_S1
DW_Switch_GREEN_OUT_F1
DW_Switch_BLUE_OUT_S1
DW_Switch_BLUE_OUT_F1
DW_Keyhole_COIN_S1
DW_Keyhole_COIN_F1
DW_Keyhole_DOUBLE_S1
DW_Keyhole_DOUBLE_F1
DW_Keyhole_SQUARE_S1
DW_Keyhole_SQUARE_F1
DW_Keyhole_WINGED_S1
DW_Keyhole_WINGED_F1
DW_Keyhole_BLOCK_S1
DW_Keyhole_BLOCK_F1
DW_Keyhole_STONE_S1
DW_Keyhole_STONE_F1
DW_Keyhole_CROSS_S1
DW_Keyhole_CROSS_F1
DW_Keyhole_GOLD_TURQUOISE_S1
DW_Keyhole_GOLD_TURQUOISE_F1
DW_Keyhole_SKELETON_S1
DW_Keyhole_SKELETON_F1
DW_Keyhole_GOLD_S1
DW_Keyhole_GOLD_F1
DW_Keyhole_TURQUOISE_S1
DW_Keyhole_TURQUOISE_F1
DW_Keyhole_EMERALD_S1
DW_Keyhole_EMERALD_F1
DW_Keyhole_RUBY_S1
DW_Keyhole_RUBY_F1
DW_Keyhole_RA_S1
DW_Keyhole_RA_F1
DW_Keyhole_MASTER_S1
DW_Keyhole_MASTER_F1
DW_Keyhole_GEM_S1
DW_Keyhole_GEM_F1
DW_Decoration_SLIME_S1
DW_Decoration_SLIME_F1
DW_Decoration_GRATING_S1
DW_Decoration_GRATING_F1
DW_Other_FOUNTAIN_LION_S1
DW_Other_FOUNTAIN_LION_F1
DW_Decoration_MANACLES_S1
DW_Decoration_MANACLES_F1
DW_Decoration_DEMON_FACE_S1
DW_Decoration_DEMON_FACE_F1
DW_Other_TORCH_HOLDER_EMPTY_S1
DW_Other_TORCH_HOLDER_EMPTY_F1
DW_Decoration_DRAGON_SCRATCHES_S1
DW_Decoration_DRAGON_SCRATCHES_F1
DW_Other_HOLES_POISON_S1
DW_Other_HOLES_POISON_F1
DW_Other_HOLES_FIREBALL_S1
DW_Other_HOLES_FIREBALL_F1
DW_Other_HOLES_DAGGER_S1
DW_Other_HOLES_DAGGER_F1
DW_Other_MIRROR_S1
DW_Other_MIRROR_F1
DW_Switch_LEVER_UP_S1
DW_Switch_LEVER_UP_F1
DW_Switch_LEVER_DOWN_S1
DW_Switch_LEVER_DOWN_F1
DW_Other_TORCH_HOLDER_FULL_S1
DW_Other_TORCH_HOLDER_FULL_F1
DW_Switch_RED_OUT_S1
DW_Switch_RED_OUT_F1
DW_Switch_EYE_S1
DW_Switch_EYE_F1
DW_Switch_BIG_OUT_S1
DW_Switch_BIG_OUT_F1
DW_Switch_CRACK_OUT_S1
DW_Switch_CRACK_OUT_F1
DW_Switch_GREEN_IN_S1
DW_Switch_GREEN_IN_F1
DW_Switch_BLUE_IN_S1
DW_Switch_BLUE_IN_F1
DW_Switch_RED_IN_S1
DW_Switch_RED_IN_F1
DW_Switch_BIG_IN_S1
DW_Switch_BIG_IN_F1
DW_Switch_CRACK_IN_S1
DW_Switch_CRACK_IN_F1
DW_Other_AMALGAM_S1
DW_Other_AMALGAM_F1
DW_Other_AMALGAM_BURNT_S1
DW_Other_AMALGAM_BURNT_F1
DW_Other_AMALGAM_EMPTY_S1
DW_Other_AMALGAM_EMPTY_F1
DW_Other_OUTSIDE_S1
DW_Other_OUTSIDE_F1
DF_FOOTPRINTS_S3
DF_FOOTPRINTS_F3
DF_FOOTPRINTS_S2
DF_FOOTPRINTS_F2
DF_FOOTPRINTS_S1
DF_FOOTPRINTS_F1
DF_Decoration_GRATE_S3
DF_Decoration_GRATE_F3
DF_Decoration_GRATE_S2
DF_Decoration_GRATE_F2
DF_Decoration_GRATE_S1
DF_Decoration_GRATE_F1
DF_Pad_LARGE_S3
DF_Pad_LARGE_F3
DF_Pad_LARGE_S2
DF_Pad_LARGE_F2
DF_Pad_LARGE_S1
DF_Pad_LARGE_F1
SmallBlank
DF_Decoration_SLIME_S3
DF_Decoration_SLIME_F3
DF_Decoration_SLIME_F2
DF_Decoration_SLIME_S1
DF_Decoration_SLIME_F1
DF_Decoration_GRATE_ROUND_S3
DF_Decoration_GRATE_ROUND_F3
DF_Decoration_GRATE_ROUND_S2
DF_Decoration_GRATE_ROUND_F2
DF_Decoration_GRATE_ROUND_S1
DF_Decoration_GRATE_ROUND_F1
DF_Pad_SMALL_S3
DF_Pad_SMALL_F3
DF_Pad_SMALL_S2
DF_Pad_SMALL_F2
DF_Pad_SMALL_S1
DF_Pad_SMALL_F1
DF_Decoration_FIREPit_S3
DF_Decoration_FIREPit_F3
DF_Decoration_FIREPit_S2
DF_Decoration_FIREPit_F2
DF_Decoration_FIREPit_S1
DF_Decoration_FIREPit_F1
DF_Decoration_CRACK_S3
DF_Decoration_CRACK_F3
DF_Decoration_CRACK_S2
DF_Decoration_CRACK_F2
DF_Decoration_CRACK_S1
DF_Decoration_CRACK_F1
DF_Pad_TINY_S3
DF_Pad_TINY_F3
DF_Pad_TINY_S2
DF_Pad_TINY_F2
DF_Pad_TINY_S1
DF_Pad_TINY_F1
DF_Decoration_PUDDLE_S3
DF_Decoration_PUDDLE_F3
DF_Decoration_PUDDLE_S2
DF_Decoration_PUDDLE_F2
DF_Decoration_PUDDLE_S1
DF_Decoration_PUDDLE_F1
DD_Patch_BASHED_F1
DD_Patch_BASHED_PORTICULLIS_F1
DD_Patch_WINDOW_RECTANGLE_F1
DD_Patch_REINFORCED_IRON_F1
DD_Patch_ORNATE_F1
DD_Patch_REINFORCED_WOOD_F1
DD_Patch_WINDOW_SEMI_CIRCLE_F1
DD_Patch_LOCK_DOOR_F1
DD_Patch_LOCK_PORTICULLIS_F1
DD_BLACK_F1
DD_Patch_LOCK_1_F1
DD_Patch_LOCK_2_F1
DD_Patch_ENERGY_F1
DD_Patch_DETERIORATED_F1
DD_Patch_BUTTON_F1
Do_Thrown_ARROW_OUTCOMING_F1
Do_Thrown_ARROW_INCOMING_F1
Do_Thrown_ARROW_S1
Do_Thrown_DAGGER_OUTCOMING_F1
Do_Thrown_DAGGER_INCOMING_F1
Do_Thrown_DAGGER_S1
Do_Thrown_AXE_UP_F1
Do_Thrown_AXE_DOWN_F1
Do_Thrown_AXE_S1
Ds_LIGHTNING_F1
Ds_LIGHTNING_S1
Do_Thrown_SLAYER_INCOMING_F1
Do_Thrown_SLAYER_OUTCOMING_F1
Do_Thrown_SLAYER_S1
Do_Thrown_STONE_CLUB_UP_F1
Do_Thrown_STONE_CLUB_DOWN_F1
Do_Thrown_STONE_CLUB_S1
Do_Thrown_CLUB_UP_F1
Do_Thrown_CLUB_DOWN_F1
Do_Thrown_CLUB_S1
Do_Thrown_POISON_DART_OUTCOMING_F1
Do_Thrown_POISON_DART_INCOMING_F1
Do_Thrown_POISON_DART_S1
Do_Thrown_SWORD_OUTCOMING_F1
Do_Thrown_SWORD_INCOMING_F1
Do_Thrown_SWORD_S1
Do_Thrown_THROWING_STAR_F1
Do_Thrown_THROWING_STAR_S1
Ds_FIREBALL_F1
Ds_ANTIMATERIAL_F1
Ds_POISON_BLOB_F1
Ds_POISON_MISSILE_F1
Ds_FIREBALL_EXPLOSION_F1
Ds_ANTIMATERIAL_EXPLOSION_F1
Ds_POISON_EXPLOSION_F1
Ds_FIREBALL_EXPLOSION_LIGHT_F0
Ds_FIREBALL_EXPLOSION_MEDIUM_F0
Ds_FIREBALL_EXPLOSION_STRONG_F0
Ds_ANTIMATERIAL_EXPLOSION_LIGHT_F0
Ds_ANTIMATERIAL_EXPLOSION_MEDIUM_F0
Ds_ANTIMATERIAL_EXPLOSION_STRONG_F0
Ds_POISON_EXPLOSION_LIGHT_F0
Ds_POISON_EXPLOSION_MEDIUM_F0
Ds_POISON_EXPLOSION_STRONG_F0
Do_CHEST_F1
Do_Thrown_Misc_CHEST_S1
Do_SCROLL_F1
Dp_FLASK_OF_WATER_F1
Do_GEM_BLUE_F1
Do_COIN_GOLD_F1
Df_DRUMSTICK_F1
Do_WATERSKIN_FULL_F1
Dc_ELVEN_F1
Dc_Feet_LEATHER_BOOTS_F1
Dc_Head_HELM_F1
Dc_Shield_F1
Dw_Staff_YEW_F1
Dw_Sword_F1
Dw_Axe_F1
Dw_BOW_F1
Dc_Neck_JEWEL_SYMA_F1
Dw_Missile_ARROW_F1
Dw_Missile_DAGGER_F1
Dk_IRON_F1
Dc_MITHRAL_F1
Dc_BODY_PLATE_F1
Dw_MACE_F1
Dc_LEGS_PLATE_F1
Dc_LEATHER_F1
Dc_GHI_F1
Df_BREAD_F1
Df_CHEESE_F1
Df_APPLE_F1
Df_CORN_F1
Dc_Feet_SUEDE_BOOTS_F1
Dw_Staff_SCEPTRE_OF_LYF_F1
Dw_Wand_WAND_F1
Dw_Wand_DRAGON_SPit_F1
Dw_MORNINGSTAR_F1
Do_COMPASS_F1
Dw_TORCH_F1
Do_WATERSKIN_EMPTY_F1
Dw_FLAMITT_F1
Do_RING_F1
Dw_Staff_THE_FIRESTAFF_F1
Do_ASHES_F1
Do_BONES_F1
Dw_Sword_VORPAL_BLADE_F1
Dw_Club_F1
Dw_Club_Stone_F1
Dw_SPEEDBOW_F1
Dw_Missile_SLAYER_F1
Dw_Missile_ROCK_F1
Dw_Missile_POISON_DART_F1
Dw_Missile_THROWING_STAR_F1
Dw_Staff_STAFF_F1
Dw_Staff_CONDUIT_F1
Dc_Head_PLATE_HELM_F1
Dc_Head_CROWN_OF_NERRA_F1
Dc_Shield_BUCKLER_F1
Dc_Feet_SANDALS_F1
Dc_Feet_PLATE_F1
Dc_Feet_ELVEN_BOOTS_F1
Dc_Neck_MOONSTONE_F1
Dc_Neck_PENDANT_FERAL_F1
Do_GEM_ORANGE_F1
Do_GEM_GREEN_F1
Dk_TOPAZ_F1
Do_MAGIC_BOX_GREEN_F1
Do_MIRROR_OF_DAWN_F1
Do_HORN_OF_FEAR_F1
Df_DRAGON_STEAK_F1
Dp_VEN_F1
Dp_BOMB_FUL_F1
Dc_BLUE_F1
Df_WORM_ROUND_F1
Df_SCREAMER_SLICE_F1
Do_ROPE_F1
Do_RABBITS_FOOT_F1
Do_CORBAMITE_F1
Dc_Neck_CHOKER_F1
Do_BOULDER_F1
Dk_LOCK_PICKS_F1
Do_MAGNIFIER_F1
Do_MAGIC_BOX_BLUE_F1
Dp_EMPTY_FLASK_F1
Dc_Feet_BOOTS_OF_SPEED_F1
Dw_Staff_THE_FIRESTAFF_PLUS_GEM_F1
Do_COIN_SILVER_F1
Dc_BODY_HALTER_F1
Dm_SCORPION_F1
Dm_SCORPION_S1
Dm_SCORPION_B1
Dm_SCORPION_A1
Dm_SLIME_PLANT_F1
Dm_SLIME_PLANT_A1
Dm_GIGGLER_F1
Dm_GIGGLER_S1
Dm_GIGGLER_B1
Dm_GIGGLER_A1
Dm_BEHOLDER_F1
Dm_BEHOLDER_A1
Dm_RAT_F1
Dm_RAT_S1
Dm_RAT_B1
Dm_RAT_A1
Dm_RUSTER_F1
Dm_RUSTER_S1
Dm_RUSTER_B1
Dm_SCREAMER_F1
Dm_SCREAMER_A1
Dm_ROCK_PILE_F1
Dm_ROCK_PILE_A1
Dm_GHOST_F1
Dm_GHOST_A1
Dm_STONE_GOLEM_F1
Dm_STONE_GOLEM_S1
Dm_STONE_GOLEM_B1
Dm_STONE_GOLEM_A1
Dm_MUMMY_F1
Dm_MUMMY_S1
Dm_MUMMY_B1
Dm_MUMMY_A1
Dm_FIRE_ELEMENTAL_F1
Dm_FIRE_ELEMENTAL_A1
Dm_SKELETON_F1
Dm_SKELETON_S1
Dm_SKELETON_B1
Dm_SKELETON_A1
Dm_COUATL_F1
Dm_COUATL_S1
Dm_COUATL_B1
Dm_COUATL_A1
Dm_VEXIRK_F1
Dm_VEXIRK_S1
Dm_VEXIRK_B1
Dm_VEXIRK_A1
Dm_WORM_F1
Dm_WORM_S1
Dm_WORM_B1
Dm_WORM_A1
Dm_OGRE_F1
Dm_OGRE_S1
Dm_OGRE_B1
Dm_OGRE_A1
Dm_WASP_F1
Dm_WASP_S1
Dm_WASP_B1
Dm_WASP_A1
Dm_KNIGHT_F1
Dm_KNIGHT_S1
Dm_KNIGHT_B1
Dm_KNIGHT_A1
Dm_FADER_1_F1
Dm_FADER_2_F1
Dm_FADER_3_F1
Dm_FADER_A1
Dm_WATER_ELEMENTAL_F1
Dm_WATER_ELEMENTAL_A1
Dm_SPIDER_F1
Dm_SPIDER_S1
Dm_SPIDER_B1
Dm_SPIDER_A1
Dm_DEMON_F1
Dm_DEMON_S1
Dm_DEMON_B1
Dm_DEMON_A1
Dm_LORD_CHAOS_F1
Dm_LORD_CHAOS_S1
Dm_LORD_CHAOS_B1
Dm_LORD_CHAOS_A1
Dm_DRAGON_F1
Dm_DRAGON_S1
Dm_DRAGON_B1
Dm_DRAGON_A1
Dm_LORD_GREY_F14
Dm_LORD_GOOD_F1
Sound_Metallic
Sound_Switch_clicking
Sound_Door
Sound_Bashing
Sound_Exploding_Fireball
Free676
Sound_Dying
Sound_Swallowing
Sound_Wounded1
Sound_Wounded2
Sound_Wounded3
Sound_Wounded4
Sound_Exploding_Spell
Sound_Slash
Sound_Teleporting
Free686
Sound_RunningIntoaWall
Sound_Monster_BigRoaring
Sound_Monster_Yelling
Sound_Monster_Screamer
Sound_Monster_Scorpion
Sound_Monster_SmallRoaring
Sound_Monster_Stealing
Texts_Objects_Names
Unknown695
Unknown696
Free697
Free698
Free699
Free700
Sound_Monster_Walking_Knight
Sound_Monster_Walking_Flyer
Sound_Monster_Walking_Humanoid
Sound_BlowingHorn
Sound_Monster_Walking_Strange
Sound_Monster_Walking_Slime
Sound_WarCrying
Sound_Monster_Walking_RockMonster
Sound_Monster_Walking_Liquid
Sound_Monster_Whiping
Sound_Monster_Walking_Heavy
Sound_Monster_Walking_Bones

